version: '3.8'

services:
  aquabot:
    build:
      context: .
      args:
        - IMAGE_TAG=${IMAGE_TAG}
    image: aquabot:${IMAGE_TAG}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
    command: ["python", "main.py"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
