version: '3.8'

services:
  aquabot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
    command: ["python", "main.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
