name: Deploy Aquabot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      id: setup_ssh
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Generate .env file
      run: |
        echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} > .env
        echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env

    - name: Sync files to server
      env:
        RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" . root@${{ secrets.SERVER_IP }}:/opt/aquabot

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /opt/aquabot
          sudo docker-compose down
          sudo docker image prune -af
          sudo docker-compose build
          sudo docker-compose up -d
